//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornax.Net {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Fornax : global::System.Configuration.ApplicationSettingsBase {
        
        private static Fornax defaultInstance = ((Fornax)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Fornax())));
        
        public static Fornax Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.dhtml</string>
  <string>.fxml</string>
  <string>.htm</string>
  <string>.html</string>
  <string>.shtml</string>
  <string>.xaml</string>
  <string>.xhtml</string>
  <string>.xml</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultDOMTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultDOMTypes"]));
            }
            set {
                this["DefaultDOMTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.eml</string>
  <string>.dbx</string>
  <string>.msg</string>
  <string>.pst</string>
  <string>.vcf</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultEmailTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultEmailTypes"]));
            }
            set {
                this["DefaultEmailTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.asp</string>\r\n  <string>.aspx</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultWebTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultWebTypes"]));
            }
            set {
                this["DefaultWebTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.ppt</string>\r\n  <string>.pptx</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultSlideTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultSlideTypes"]));
            }
            set {
                this["DefaultSlideTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.xl</string>
  <string>.xlr</string>
  <string>.xls</string>
  <string>.xlsm</string>
  <string>.xlsx</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultSSheetTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultSSheetTypes"]));
            }
            set {
                this["DefaultSSheetTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.mp3</string>\r\n  <string>.mp4</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultMediaTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultMediaTypes"]));
            }
            set {
                this["DefaultMediaTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.gif</string>
  <string>.jpeg</string>
  <string>.jpg</string>
  <string>.png</string>
  <string>.tiff</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultImageTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultImageTypes"]));
            }
            set {
                this["DefaultImageTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.ans</string>
  <string>.ascii</string>
  <string>.c</string>
  <string>.cs</string>
  <string>.java</string>
  <string>.txt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultPlainTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultPlainTypes"]));
            }
            set {
                this["DefaultPlainTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.csv</string>
  <string>.doc</string>
  <string>.docx</string>
  <string>.epub</string>
  <string>.pdf</string>
  <string>.rtf</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultTextTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultTextTypes"]));
            }
            set {
                this["DefaultTextTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.gzip</string>\r\n  <string>.rar</string>\r\n  <string>.zip</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection DefaultZipTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultZipTypes"]));
            }
            set {
                this["DefaultZipTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.dhtml</string>
  <string>.fxml</string>
  <string>.htm</string>
  <string>.html</string>
  <string>.shtml</string>
  <string>.xaml</string>
  <string>.xhtml</string>
  <string>.xml</string>
  <string>.eml</string>
  <string>.dbx</string>
  <string>.msg</string>
  <string>.pst</string>
  <string>.vcf</string>
  <string>.asp</string>
  <string>.aspx</string>
  <string>.xl</string>
  <string>.xlr</string>
  <string>.xls</string>
  <string>.xlsm</string>
  <string>.xlsx</string>
  <string>.ppt</string>
  <string>.pptx</string>
  <string>.mp3</string>
  <string>.mp4</string>
  <string>.gif</string>
  <string>.jpeg</string>
  <string>.jpg</string>
  <string>.png</string>
  <string>.tiff</string>
  <string>.ans</string>
  <string>.ascii</string>
  <string>.c</string>
  <string>.cs</string>
  <string>.java</string>
  <string>.txt</string>
  <string>.csv</string>
  <string>.doc</string>
  <string>.docx</string>
  <string>.epub</string>
  <string>.pdf</string>
  <string>.rtf</string>
  <string>.gzip</string>
  <string>.rar</string>
  <string>.zip</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultTypes"]));
            }
            set {
                this["DefaultTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomTypes"]));
            }
            set {
                this["CustomTypes"] = value;
            }
        }
    }
}
