//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornax.Net.Bot.Local {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Daemon : global::System.Configuration.ApplicationSettingsBase {
        
        private static Daemon defaultInstance = ((Daemon)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Daemon())));
        
        public static Daemon Default {
            get {
                return defaultInstance;
            }
        }
    }
}
