//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornax.Net.Bot.Net {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class FornaxBot : global::System.Configuration.ApplicationSettingsBase {
        
        private static FornaxBot defaultInstance = ((FornaxBot)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FornaxBot())));
        
        public static FornaxBot Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GetRobot {
            get {
                return ((bool)(this["GetRobot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DepthofSearch {
            get {
                return ((int)(this["DepthofSearch"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.txt</string>\r\n  <string>.pdf</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FileTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileTypes"]));
            }
            set {
                this["FileTypes"] = value;
            }
        }
    }
}
